[mgr]
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

prepend_keymap = [
    { on = [ "g", "c" ], run = "cd ~/.dotfiles", desc = "Go to ~/.dotfiles" },
	{ on = [ "g", "p" ], run = "cd ~/Projects", desc = "Go to ~/Projects" },
] 

append_keymap = [
]

