"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [2, 3, 5]
linemode = "mtime"
show_hidden = true
show_symlink = false

[preview]
max_width = 9999
max_height = 9999
image_quality = 90

[opener]
edit = [{ run = '$EDITOR "$@"', desc = "$EDITOR", block = true }]
open = [{ run = 'xdg-open "$1"', desc = "Open" }]
extract = [{ run = 'ya pub extract --list "$@"', desc = "Extract here" }]
play = [{ run = 'mpv "$@"', orphan = true }]

[open]
rules = [
    { name = "*/", use = [
        "edit",
        "open",
    ] },
    { mime = "text/*", use = [
        "edit",
    ] },
    { mime = "image/*", use = [
        "open",
    ] },
    { mime = "{audio,video}/*", use = [
        "play",
    ] },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [
        "extract",
    ] },
    { mime = "application/{json,ndjson}", use = [
        "edit",
    ] },
    { mime = "*/javascript", use = [
        "edit",
    ] },
    { mime = "inode/empty", use = [
        "edit",
    ] },
    # Fallback
    { name = "*", use = [
        "open",
        "edit",
        "extract",
        "play",
    ] },
]
