"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"


[mgr]
ratio = [2, 3, 5]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "mtime"
show_hidden = true
show_symlink = true
scrolloff = 8
mouse_events = ["click", "scroll"]
title_format = "Yazi:{cwd}"


[preview]
wrap = "no"
tab_size = 4

max_width = 8000
max_height = 8000
cache_dir = ""
image_delay = 0
image_filter = "lanczos3"
image_quality = 80
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [{ run = '$EDITOR "$@"', desc = "$EDITOR", block = true, for = "unix" }]
open = [{ run = 'xdg-open "$1"', desc = "Open", orphan = true, for = "linux" }]
extract = [
    { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]


[open]
rules = [
    { name = "*/", use = [
        "open",
    ] },
    { mime = "text/*", use = [
        "edit",
    ] },
    { mime = "image/*", use = [
        "open",
    ] },
    { mime = "{audio,video}/*", use = [
        "play",
    ] },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [
        "extract",
    ] },
    # Fallback
    { name = "*", use = [
        "edit",
        "open",
        "extract",
        "play",
    ] },
]

[tasks]
image_bound = [0, 0]